- src/i18n/en.js
- src/i18n/ko.js
- src/routes/JWallet/sagas/currencies.js
- src/utils/isJNTContract.js
* add ability to remove previously added JNT by user
* add uniq check for token symbol
> Add features:

- config/webpack.config.prod.js
To get working isolation for styles of components
> Remove css minimize option for prod

- src/components/CurrencyItem/CurrencyItem.js
This reverts commit 5566d4589b16ab605ada0358278ee7c164c895df.
> Revert "Fix tokens url"

- src/components/base/JInput/JInput.js
render and placeholder can be null (defaultProps), fix flow types
> fix flowtypes

- src/routes/Settings/SettingsIndexView.js
> WEB-7 Settings typo

- .idea/codeStyles/Project.xml
- .idea/vcs.xml
> Updating .idea settings, new directories were marked

- src/components/base/JIcon/jIcon.scss
- src/components/base/JThumbnail/JThumbnail.js
- src/public/assets/icons/new-pack/large/screen-no-favorites.svg
- src/public/assets/icons/new-pack/medium/favorite-address-add-gray.svg
- src/routes/Favorites/FavoritesIndexView.js
- src/routes/Favorites/favoritesView.scss
- src/styles/icons.scss
Add empty list management
Add link to add favorite
> Cover favorites edge cases

- src/components/DoubleInput/doubleInput.scss
- src/components/PriorityPicker/PriorityPicker.js
> Correct position close button, correct send props in DoubleInput

- src/routes/DigitalAssets/routes/Send/sagas/digitalAssetsSend.js
- src/store/configureStore.js
Everything good with localhost. This issue appears only in our prod env
>  Debug send transaction in prod

- src/main.js
- src/public/css/style.css
- src/public/index.html
- src/public/js/capabilities.js
Fallback page is show accordingly for this way
* Fallback page for showing inaccessible features of browser was added
* Capability checking was added
> JWWEB-35 Checking indexedDB and localStorage API in browser

- package-lock.json
- package.json
- src/routes/DigitalAssets/routes/Send/sagas/digitalAssetsSend.js
- src/store/configureStore.js
- webpack.config.js
- adds custom minification config (extended from webpack built-in default config)
- removes debug info
> JWWEB-439: fix webpack BigNumber minification

- src/public/index.html
Add IP anonymization for Google Analytics compliance with GDPR
> GDPR compliant analytics

- package-lock.json
- src/components/QRCode/QRCode.js
- src/components/QRCode/qrCode.scss
> JWWEB-440 Removing action buttons (save/copy) for QRCode component

- src/components/PasswordField/PasswordField.js
- src/components/base/JInput/JInput.js
- src/components/base/JInput/jInput.scss
Padding for password fields with indicator was added
> JWWEB-484 Padding for password fields with indicator

- package-lock.json
- src/data/agreements.js
- src/middlewares/redirect/filters/agreement.js
- src/middlewares/redirect/filters/firstTime.js
- src/middlewares/redirect/filters/index.js
- src/middlewares/redirect/filters/readonly.js
- src/middlewares/redirect/filters/root.js
- src/middlewares/redirect/filters/selectedWallet.js
- src/middlewares/redirect/filters/upgrade.js
- src/middlewares/redirect/filters/walletsAddresses.js
- src/middlewares/redirect/index.js
- src/routes/Agreements/AgreementsView.js
- src/routes/Upgrade/UpgradeView.js
- src/routes/Upgrade/UpgradeViewContainer.js
- src/routes/Wallets/routes/Addresses/sagas/walletsAddresses.js
- src/routes/Wallets/routes/Backup/WalletsBackupView.js
- src/routes/Wallets/routes/Backup/sagas/walletsBackup.js
- src/routes/index.js
- src/store/configureStore.js
- src/utils/analytics/ga.js
The main idea was to encapsulate all the routing rules in a single file, so future refactor would be more simple.
There is also a hack suggested by @IViol (thnx again!) with redirect happening after all redux-persist hydration events.
> JWWEB-437: Routing

- src/components/WalletFace/walletFace.scss
> JWWEB-455 correct wallets view with open actions

- flow-typed/config.js
- package-lock.json
- package.json
- src/AppContainer.js
- src/components/SingularTabBlockScreen/SingularTabBlockScreen.js
- src/components/SingularTabBlockScreen/index.js
- src/components/SingularTabBlockScreen/singularTabBlockScreen.scss
- src/components/base/JIcon/jIcon.scss
- src/components/base/JThumbnail/JThumbnail.js
- src/config.js
- src/styles/icons.scss
- src/utils/browser/index.js
- src/utils/browser/startSessionWatcher.js
Watcher for monitoring multiple app instances in tabs of browser was added
> JWWEB-463 Work in multiple tabs

- src/components/base/JInput/JInput.js
Overlay of double messages was fixed
> JWWEB-546 Overlay of JInput messages was fixed

- src/components/ButtonWithConfirm/ButtonWithConfirm.js
- src/routes/Wallets/routes/Delete/WalletsDeleteView.js
Routing on the delete wallet page was refactored
> JWWEB-527 Delete wallet - wrong redirect if user pressing "nope, stop it"

- src/routes/DigitalAssets/routes/Receive/DigitalAssetsReceiveView.js
- src/routes/DigitalAssets/routes/Receive/DigitalAssetsReceiveViewContainer.js
Receive address was refactored for showing only current address
> JWWEB-550 Limit list of addresses on Receive Assets screen to current

- src/components/InputButton/InputButton.js
- src/components/base/JInput/JInput.js
- src/components/base/JInput/jInput.scss
JWWEB-537
Cross is superimposed on the text in the Comment field
> Input with icon

- src/routes/Transactions/TransactionsIndexViewContainer.js
- src/routes/Transactions/routes/Asset/TransactionsAssetViewContainer.js
- src/utils/transactions/searchTransactions.js
Searching of transactions was improved
> JWWEB-534 Search in the transaction list is not working

- src/components/base/JSearch/JSearch.js
JSearch clears value on unmount
> JWWEB-470 Search results are displayed after back from transactions through digital asset button

- src/routes/DigitalAssets/routes/Grid/DigitalAssetsGridViewContainer.js
- src/utils/digitalAssets/compareDigitalAssetsByBalance.js
Now we take into account number of decimals when we sort by balance
> JWWEB-566: incorrect sorting

- .stylelintrc
[Description of the rule](https://stylelint.io/user-guide/rules/no-descending-specificity)
> Enable no-descending-specificity stylelint rule

- src/errors/JError.js
- src/errors/JError.test.js
For examples of usage, please refer to file with tests.
> Add base error

- flow-typed/redux/wallets.js
- src/components/CopyableField/CopyableField.js
- src/data/lang/en.po
- src/middlewares/analyticsMiddleware/newWalletEvents.js
- src/middlewares/analyticsMiddleware/userParams.js
- src/routes/Wallets/modules/wallets.js
- src/routes/Wallets/routes/Backup/WalletsBackupView.js
- src/routes/Wallets/routes/Backup/sagas/walletsBackup.js
- src/routes/Wallets/routes/Create/WalletsCreateView.js
- src/routes/Wallets/routes/Create/WalletsCreateViewContainer.js
- src/routes/Wallets/routes/Create/modules/walletsCreate.js
- src/routes/Wallets/routes/Create/sagas/walletsCreate.js
- src/routes/Wallets/routes/Import/modules/walletsImport.js
- src/routes/Wallets/routes/Import/sagas/walletsImport.js
- src/workers/wallets/worker.js
- src/workers/wallets/wrapper.js
- stories/components/CopyableField.stories.js
Also:
- Simplify wallet creation for both Create and Import
- Move copy logic to CopyableField
- Update Google Analytics events
> JWWEB-703: Add backup action to the "Create Wallet" process

- src/public/index.html
Add og prefix for html
Fix description text
Update og attribute names
Add twitter share data
> JWWEB-579: Update social share data

- .idea/watcherTasks.xml
> ESLint fix on save file in webstorm

- src/components/TransactionItemNew/TransactionItem.js
- src/components/TransactionItemNew/TransactionsItem.stories.js
- src/components/TransactionItemNew/transactionItem.m.scss
- New story for single transaction was added
- Tiny style fixes
- Titles for long text was added to title and note area
> JWWEB-736 Stories for transaction item

- src/components/base/JPicker/Body/JPickerBody.js
- src/components/base/JPicker/Body/jPickerBody.m.scss
- src/components/base/JPicker/Current/JPickerCurrent.js
- src/components/base/JPicker/Current/jPickerCurrent.m.scss
- src/pages/Send/components/AssetPicker/AssetPicker.js
Fixes:
1. Remove search
2. There is no hand on the cursor
3. Hover for expended list adding to hover of the selected item and they are imposed
4. There is a shadow on the selected item from the expended list
5. Expanded list is not collapsed while clicking to the arrow
6. The font of the selected item should be Semi-bold(600)
> JWWEB-717 - Fix asset picker issues

- src/components/base/Header/header.m.scss
- src/components/base/JRaisedButton/JRaisedButton.js
- src/components/base/JRaisedButton/jRaisedButton.m.scss
- src/pages/Home/HomeView.js
- src/pages/Home/home.m.scss
Fixed margins and padding for search panel in assets section, added themes for additional buttons in JRaisedButton
> JWWEB-735 Handle comments from QA and design

- src/components/TransactionItemNew/TransactionItem.js
- src/components/TransactionItemNew/transactionItem.m.scss
Simplify code a little
Fix design bugs
> JWWEB-736: Fix TransactionItem

- src/components/NewWalletButtons/newWalletButtons.m.scss
- src/components/base/JInputField/jInputField.m.scss
- src/components/base/JTextArea/jTextArea.m.scss
- src/styles/_base.scss
Rename secondary shadow to be the same as in design spec
Add border radius for input field
> JWWEB-728: Update JInput

- src/components/TransactionItemNew/TransactionItem.js
- src/pages/Home/components/AssetItem/AssetItem.js
- src/utils/formatters/formatAssetBalance.js
- src/utils/formatters/formatTransactionAmount.js
- src/utils/formatters/index.js
Moved formatters from component to utils
> Formatters for transaction amount

- src/components/FieldPreview/FieldPreview.js
- src/components/FieldPreview/FieldPreview.stories.js
- src/components/FieldPreview/tests/FieldPreview.test.js
To props was added `copyMessage` property for showing correct text in snackbars on copy.
> JWWEB-793 Update API of component for snackbar view

- src/components/base/JSwitch/JSwitch.js
- src/components/base/JSwitch/JSwitch.stories.js
- src/components/base/JSwitch/jSwitch.scss
Needed for gas price filed inside send asset
> Refactor JSwitch

- src/pages/WalletsImport/WalletsImport.js
- src/pages/WalletsImport/dataMessage.js
- src/store/plugins/walletsPlugin.js
- Skip password step for read only wallets (address, xpub)
- Update validating of ETH address by checksum (EIP55)
> Improve importing of read only wallets

- src/components/ContactsItemDetails/ContactsItemDetailsInternal.js
- src/components/ContactsItemDetails/contactsItem.m.scss
- src/components/base/Button/button.m.scss
- src/pages/ContactsItemEdit/ContactsItemEditView.js
- src/styles/_base.scss
Issues founded by QA were fixed
> Fixes for contacts pages

- src/pages/SettingsCurrency/SettingsCurrency.js
- src/pages/SettingsCurrency/components/CurrencyPicker/CurrencyPicker.js
- src/pages/SettingsCurrency/settingsCurrency.m.scss
- src/pages/SettingsLanguage/SettingsLanguage.js
- src/pages/SettingsLanguage/components/LanguagePicker/LanguagePicker.js
- src/pages/SettingsLanguage/settingsLanguage.m.scss
- src/pages/index.js
This PR based on language picker PR (https://github.com/jibrelnetwork/jwallet-web/pull/880). Merge that first
>  JWWEB-865, JWWEB-866 Currency and language pages markup
